# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_author_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_posted', models.DateTimeField()),
                ('raw_comment', models.TextField()),
                ('clean_comment', models.TextField()),
                ('asset_url', models.URLField(blank=True, null=True)),
                ('likes', models.IntegerField()),
                ('num_bold', models.IntegerField()),
                ('num_uppercase', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('homepage', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Outlet'),
        ),
        migrations.AddField(
            model_name='author',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Outlet'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('api_author_id', 'outlet')]),
        ),
    ]
