# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='api_author_id',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='author',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.TextField(),
        ),
    ]
