# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170225_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outlet',
            new_name='Forum',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='outlet',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='outlet',
            new_name='forum',
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('api_author_id', 'forum')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('api_comment_id', 'forum')]),
        ),
    ]
