# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_accuracy_modelstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuracy',
            name='train_len',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
